Repository 5th-A/ASAC-5th-airbnb, pull requests merged in 2024-05, with the labels that each got.

#2 #1 [FE] design: 서치 바 컴포넌트 UI 작업
  src/App.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchButton.jsx
Labels: 🐶 FE, 👩‍🎨 design

#4 #3 [FE] feat: 숙소-카드-구현
  package-lock.json
  package.json
  src/App.jsx
  src/components/RoomList/RoomCard.css
  src/components/RoomList/RoomCard.jsx
  src/components/RoomList/RoomList.jsx
  src/image/LikeButton/fullheart.png
  src/image/LikeButton/heart.png
Labels: ✨ feature

#7 #6 [FE] feat: airbnb-숙소-검색-및-리스트-페이지의-footer-생성
  src/App.jsx
Labels: 🐶 FE, 👩‍🎨 design

#10 #6 [FE] design: Airbnb 숙소 검색 및 리스트 페이지의 Footer 생성
  src/components/Footer/Footer.jsx
  src/image/Footer/facebook.png
  src/image/Footer/instagram.png
  src/image/Footer/naverblog.png
  src/image/Footer/naverpost.png
  src/image/Footer/twitter.png
Labels: 🐶 FE, 👩‍🎨 design

#9 #5 [FE] feat: 숙소 리스트 구현
  .prettierrc
  src/components/RoomList/RoomCard.css
  src/components/RoomList/RoomCard.jsx
  src/components/RoomList/RoomList.jsx
Labels: ✨ feature, 🐶 FE, 👩‍🎨 design

#14 #11 [FE] design : 최상단바 네이게이션바 UI구현
  src/App.jsx
  src/components/Container/Container.jsx
Labels: 🐶 FE, 👩‍🎨 design

#16 #12 [FE] design: 카테고리 바 컴포넌트 UI 작업
  src/App.jsx
  src/components/Category/Category.jsx
  src/components/Category/category.json
Labels: 🐶 FE, 👩‍🎨 design

#17 #15 [FE] design: 작은 서치 바 컴포넌트 UI
  src/App.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchButton.jsx
  src/components/SearchBar/SmallSearchBar.jsx
Labels: ♻️ refactor, 🐱 BE, 👩‍🎨 design

#26 #19 [FE] feature 상세페이지 정보표시+우측계산기 작업
  src/DetailPage.jsx
  src/assets/airconditioner.svg
  src/assets/countryside.svg
  src/assets/extensionArrow.svg
  src/assets/freecancel.svg
  src/assets/guestPrefer_Left.svg
  src/assets/guestPrefer_Right.svg
  src/assets/selfCheckIn.svg
  src/assets/star.svg
  src/assets/superhost.svg
  src/assets/wifi.svg
  src/components/DetailRoomInfo/DetailRoomInfo.jsx
  src/main.jsx
  src/roomDetail.json
  tailwind.config.js
Labels: ✨ feature, 🐶 FE, 👩‍🎨 design

#30 #19 [FE] refactor: 상세페이지 정보표시 컴포넌트 작업
  src/components/DetailRoomInfo/DetailRoomInfo.jsx
  tailwind.config.js
Labels: ♻️ refactor

#33 #32 [FE] feature: 카드리스트 기능구현
  src/assets/TV.svg
  src/assets/heater.svg
  src/assets/laundryMachine.svg
  src/assets/likeButton_empty.svg
  src/assets/likeButton_full.svg
  src/assets/locationRate.svg
  src/assets/nextArrow.svg
  src/assets/prevArrow.svg
  src/components/RoomList/RoomCard.css
  src/components/RoomList/RoomCard.jsx
  src/components/RoomList/RoomList.jsx
  src/roomDetail.json
  tailwind.config.js
Labels: ✨ feature, 🐶 FE, 👩‍🎨 design

#21 #20 [FE] design: 상세 페이지 이미지 UI 구현
  src/components/MainImage/Mainimage.jsx
  src/components/MainImage/roomDetail.json
Labels: 🐶 FE, 👩‍🎨 design

#27 #18 [FE] design, feat: 예약 달력 컴포넌트 UI 및 기능 제작
  src/App.jsx
  src/components/Calendar/Calendar.jsx
  src/components/Calendar/CalendarComponent.jsx
  src/components/Calendar/CalendarContainer.jsx
  src/components/Calendar/DetailPageCalendarDisplay.jsx
  src/components/Category/Category.jsx
Labels: ✨ feature, 🐶 FE, 👩‍🎨 design

#25 #22 [FE] design : 호스트 소개 컴포넌트 UI 작업
  src/assets/hosts/badge.svg
  src/assets/hosts/superHost.svg
  src/assets/hosts/superHostRed.svg
  src/components/HostIntroduction/HostIntroduction.jsx
  src/data/RoomInfo.json
Labels: ✨ feature, 🐶 FE, 👩‍🎨 design

#34 #28 [FE] design: 세부정보 댓글컴포넌트 UI작업
  src/components/Comment/Comment.jsx
  src/components/Comment/comment.json
Labels: 🐶 FE, 👩‍🎨 design

#29 #23 [FE] design: 상세페이지 숙박장소 및 편의시설 UI
  src/assets/svg-export/svgexport-47.svg
  src/assets/svg-export/svgexport-48.svg
  src/assets/svg-export/svgexport-49.svg
  src/assets/svg-export/svgexport-50.svg
  src/assets/svg-export/svgexport-51.svg
  src/assets/svg-export/svgexport-52.svg
  src/assets/svg-export/svgexport-53.svg
  src/assets/svg-export/svgexport-54.svg
  src/assets/svg-export/svgexport-55.svg
  src/assets/svg-export/svgexport-56.svg
  src/components/AccommodationDetails/AccommodationDetails.jsx
  src/components/Aments/Amenities.jsx
  src/components/Aments/amenities.json
Labels: 🐶 FE, 👩‍🎨 design
