Repository 5th-A/ASAC-5th-airbnb, pull requests merged in 2024-06, with the labels that each got.

#41 #39 [FE] feature: 상세페이지 계산기 모달 구현
  package-lock.json
  package.json
  src/app/layout.jsx
  src/app/rooms/[id]/page.jsx
  src/components/Calendar/CalendarContainer.jsx
  src/components/Calendar/DetailPageCalendarDisplay.jsx
  src/components/DetailRoomInfo/DetailRoomInfo.jsx
  src/components/Header/Header.jsx
  src/components/Header/SmallHeader.jsx
  src/components/Modal/GuestCalendarModal.jsx
  src/components/Modal/GuestCountModal.jsx
  src/data/roomDetail.json
  src/redux/providers.jsx
  src/redux/slices/calendarSlice.js
  src/redux/slices/guestCountSlice.js
  src/redux/store.js
Labels: ✨ feature, 🐶 FE, 🔧chore, 👩‍🎨 design

#43 #42 [FE] refactor: imgae 태그 변경 작업
  next.config.mjs
  src/app/rooms/[id]/page.jsx
  src/components/Calendar/Calendar.jsx
  src/components/DetailRoomInfo/DetailRoomInfo.jsx
  src/components/Modal/GuestCalendarModal.jsx
  src/components/Modal/GuestCountModal.jsx
  src/components/RoomList/RoomCard.jsx
Labels: ♻️ refactor, 🐶 FE, 📚docs, 👩‍🎨 design

#50 #40 [FE] feat: 서치 바 모달 구현
  public/assets/searchBar/searchButton.svg
  src/components/Header/Header.jsx
  src/components/Header/SmallHeader.jsx
  src/components/SearchBar/MainSearchBar/DateArea.jsx
  src/components/SearchBar/MainSearchBar/Dropdown.jsx
  src/components/SearchBar/MainSearchBar/GuestArea.jsx
  src/components/SearchBar/MainSearchBar/SearchBar.jsx
  src/components/SearchBar/MainSearchBar/SearchButtonArea.jsx
  src/components/SearchBar/MainSearchBar/WhereArea.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SmallSearchBar.jsx
  src/data/cities.json
Labels: ✨ feature, 🐶 FE, 👩‍🎨 design

#52 #38 [FE] design: 댓글버튼 클릭시 Modal 띄우기
  package-lock.json
  package.json
  public/assets/header/defaultprofile.svg
  public/assets/svg-export/search.svg
  src/app/rooms/[id]/page.jsx
  src/components/Comment/Comment.jsx
  src/components/Header/Header.jsx
  src/components/Modal/Modal.jsx
  src/data/comment.json
Labels: 🐶 FE, 👩‍🎨 design

#54 #44 feat: 메인페이지 카드리스트 링크 설정
  src/components/RoomList/RoomCard.jsx
  src/components/RoomList/RoomList.jsx
Labels: ✨ feature, 🐶 FE

#53 #48[FE] feat: 회원가입 모달
  src/components/Header/Header.jsx
  src/components/Modal/SignUpModal.jsx
Labels: ✨ feature, 🐶 FE, 👩‍🎨 design

#56 #51 [FE] refactor : 서치 바 상태 redux
  src/components/Header/Header.jsx
  src/components/SearchBar/MainSearchBar/Dropdown.jsx
  src/components/SearchBar/MainSearchBar/GuestArea.jsx
  src/components/SearchBar/MainSearchBar/GuestContent.jsx
  src/components/SearchBar/MainSearchBar/SearchBar.jsx
Labels: ✨ feature, ♻️ refactor, 🐶 FE

#57 Fe/feature/#47 메인페이지 필터 버튼 모달 UI
  src/components/Category/Category.jsx
  src/components/Filter/Bedroom.jsx
  src/components/Filter/Facilities.jsx
  src/components/Filter/FilterModal.jsx
  src/components/Filter/PriceRangeModal.jsx
  src/components/Filter/RoomType.jsx
Labels: ✨ feature, 🐶 FE, 👩‍🎨 design

#60 #59 [FE] design: 세부 레이아웃 조절
  public/assets/header/global.svg
  public/assets/header/loginMenu.svg
  src/app/layout.jsx
  src/app/page.jsx
  src/app/rooms/[id]/page.jsx
  src/components/Category/Category.jsx
  src/components/Comment/Comment.jsx
  src/components/DetailRoomInfo/DetailRoomInfo.jsx
  src/components/Header/Header.jsx
  src/components/Header/SmallHeader.jsx
  src/components/MainImage/Mainimage.jsx
  src/components/Modal/SignUpModal.jsx
  src/components/RoomList/InfiniteList.jsx
  src/components/RoomList/RoomCard.jsx
  src/components/RoomList/RoomList.jsx
  src/components/SearchBar/MainSearchBar/DateArea.jsx
  src/components/SearchBar/MainSearchBar/GuestArea.jsx
  src/components/SearchBar/MainSearchBar/GuestContent.jsx
  src/components/SearchBar/MainSearchBar/SearchBar.jsx
  src/components/SearchBar/MainSearchBar/SearchButtonArea.jsx
  src/components/SearchBar/MainSearchBar/WhereArea.jsx
  src/redux/slices/guestCountSlice.js
  tailwind.config.js
Labels: 🐶 FE, 👩‍🎨 design

#62 #61 [FE] chore: 빌드 대비 수정
  src/app/api/route.js
  tsconfig.json
Labels: 🐶 FE, 🔧chore, 🥺 bug

#67 #64 [FE] refactor : 숙소목록 fetch추가
  public/RoomList.json
  src/app/page.jsx
  src/components/DetailRoomInfo/DetailRoomInfo.jsx
  src/components/MainPageWrapper/MainPageWrapper.jsx
  src/components/RoomList/InfiniteList.jsx
  src/components/RoomList/RoomCard.jsx
  src/components/RoomList/RoomList.jsx
Labels: ♻️ refactor, 🐶 FE

#69 #64 [FE] design: 메인페이지 레이아웃 조정
  src/components/Category/Category.jsx
  src/components/DetailRoomInfo/DetailRoomInfo.jsx
Labels: 🐶 FE, 👩‍🎨 design

#73 #70 [FE] refactor: 숙소정보 예약UI 리팩토링
  public/HostInfo.json
  public/RoomInfo.json
  src/components/DetailRoomInfo/Calculator.jsx
  src/components/DetailRoomInfo/DetailRoomInfo.jsx
  src/components/HostIntroduction/HostIntroduction.jsx
Labels: ♻️ refactor, 🐶 FE

#79 #78 [FE] feat: 서치쿼리구조작성
  src/app/page.jsx
  src/components/Filter/Bedroom.jsx
  src/components/Filter/FilterModal.jsx
  src/components/MainPageWrapper/MainPageWrapper.jsx
Labels: ✨ feature, ♻️ refactor, 🐶 FE

#82 #81 [FE] fix: 버그 수정
  src/components/Category/Category.jsx
  src/components/DetailRoomInfo/DetailRoomInfo.jsx
  src/components/MainImage/Mainimage.jsx
  src/components/MainPageWrapper/MainPageWrapper.jsx
Labels: ♻️ refactor, 🐶 FE, 🥺 bug

#71 #66 [FE] feat: 메인 이미지 상태 추가 및 fetch
  public/amenities.json
  src/components/Aments/Amenities.jsx
  src/components/MainImage/ButtonGroup.jsx
  src/components/MainImage/Mainimage.jsx
Labels: ✨ feature, 🐶 FE

#84 #75 feat : 검색 페이지 fetch 틀 구현
  public/SearchRoom.json
  src/app/s/[city]/page.jsx
  src/components/RoomList/SearchRoomList.jsx
  src/components/SearchBar/MainSearchBar/GuestArea.jsx
  src/components/SearchBar/MainSearchBar/SearchBar.jsx
  src/components/SearchBar/MainSearchBar/SearchButtonArea.jsx
Labels: ✨ feature, 🐶 FE

#86 #85 [FE] feat : 호스트정보 api 연결
  src/app/api/GetHostInfo.jsx
  src/app/rooms/[id]/page.jsx
  src/components/HostIntroduction/HostIntroduction.jsx
Labels: ✨ feature, 🐶 FE
